Name: RAHUL YADAV
Class: SYIT
Roll no. : S051
Date - 05/08/2026

Python for Data Structure
Practical No.4

a. Write a python code to create Numpy Array.

In [28]:
import numpy as np


In [29]:
a = np.array([1,2,3])
print(a)

[1 2 3]


b. Write a python code to demonstrate basic operations on single array.

In [30]:
print(a + 3)
print(a * 2)

[4 5 6]
[2 4 6]


c. Write a python code to create array with 10 elements and slice element
from 1st to 5th element.

In [31]:
b = np.array([1,2,3,4,5,6,7,8,9,10])
print(b[0:5])

[1 2 3 4 5]


d. Write a python code to sort an array alphabetically.

In [32]:
name = np.array(["Rahul","Nitesh","Kaushal","Jay"])
print(np.sort(name))

['Jay' 'Kaushal' 'Nitesh' 'Rahul']


e. Write a python code to create a filter array that will return maximum
values from an array.

In [33]:
price = np.array([300,200,500,700,800,1000])
print(price[price>200])

[ 300  500  700  800 1000]
